### ISSUE TITLE
Test Type Items fails validation

### ISSUE THREAD

**Issue by lordarokh** [microsoft/testbase#34]
Hi There,

When we use "Test Types - Get" API, it returns the following 3 items:

- Out-of-Box-Test
- Functional-Test
- Flow-Driven-Test

We use these values to generate our JSON file. However, when we create a package with the setting "OutofBoxTest" ("-" chars are removed), we get the following validation error response:

"code":"EnumCaseMismatch","message":"Enum does not match case for: OutofBoxTest

When we check the packages that are already created, they contain the following value "OutOfBoxTest" ("-" chars are removed).  When we compare the value returned from "Test Types - Get" API, we saw that the "OutofBoxTest" is not exactly as "OutOfBoxTest" and the "O" letter in "of" is in lower case. And this issue causes a validation error when we create a package via the API.
Therefore, the values that are returned from "Test Types - Get" should be rectified as :

- Out-Of-Box-Test
- Functional-Test
- Flow-Driven-Test

Thanks in advance.

**Comment by yazeng** [comment]
Hi Tolga,
Thank you for reporting our second issue! 
Yes, this is a bug and we have filed an internal bug to track and fix it.

Thanks,
Yan

**Comment by yazeng** [comment]
Hi @lordarokh, the bug is fixed. You can have a try.
